title: Your awesome title
author: GitHub User
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This is my super awesome security blog where I fail at all kinds of crackmes and challenges
# social links
twitter_username: @fk-u
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
